/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorycashierinsystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author student.admin
 */
public class SignUp extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    Statement st;
    public static int user = 0 ;
    
    public SignUp() {
        initComponents();
this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jemail = new javax.swing.JTextField();
        jpassword = new javax.swing.JPasswordField();
        jfirstname = new javax.swing.JTextField();
        jrole = new javax.swing.JComboBox<>();
        jlastname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlogin1 = new javax.swing.JLabel();
        jlogin3 = new javax.swing.JLabel();
        jlogin4 = new javax.swing.JLabel();
        jlogin2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel2.setText("Role : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(500, 590, 100, 33);

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel5.setText("sign  I N");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(620, 90, 180, 60);

        jLabel3.setFont(new java.awt.Font("Monospaced", 2, 18)); // NOI18N
        jLabel3.setText("Go back to login_Page!");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(610, 700, 280, 33);

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel1.setText("Lastname :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(500, 290, 150, 33);

        jemail.setFont(new java.awt.Font("Monospaced", 2, 18)); // NOI18N
        jemail.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jemail);
        jemail.setBounds(570, 420, 370, 40);

        jpassword.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jpassword.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(jpassword);
        jpassword.setBounds(570, 520, 374, 40);

        jfirstname.setFont(new java.awt.Font("Monospaced", 2, 18)); // NOI18N
        jfirstname.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jfirstname);
        jfirstname.setBounds(570, 230, 370, 40);

        jrole.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jrole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "Cashier" }));
        jPanel1.add(jrole);
        jrole.setBounds(660, 590, 140, 41);

        jlastname.setFont(new java.awt.Font("Monospaced", 2, 18)); // NOI18N
        jlastname.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jlastname);
        jlastname.setBounds(570, 330, 370, 40);

        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel7.setText("Firstname :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(500, 190, 170, 33);

        jLabel6.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel6.setText("Email : ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(500, 380, 112, 33);

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel4.setText("Password : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(500, 480, 154, 33);

        jlogin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorycashierinsystem/img/vanie.png"))); // NOI18N
        jlogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlogin1MouseClicked(evt);
            }
        });
        jPanel1.add(jlogin1);
        jlogin1.setBounds(130, 510, 70, 210);

        jlogin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorycashierinsystem/img/Untitled-1.png"))); // NOI18N
        jlogin3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlogin3MouseClicked(evt);
            }
        });
        jPanel1.add(jlogin3);
        jlogin3.setBounds(150, 220, 230, 210);

        jlogin4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorycashierinsystem/img/Untitled-1.png"))); // NOI18N
        jlogin4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlogin4MouseClicked(evt);
            }
        });
        jPanel1.add(jlogin4);
        jlogin4.setBounds(150, 220, 230, 210);

        jlogin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorycashierinsystem/img/SIGN UP.png"))); // NOI18N
        jlogin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlogin2MouseClicked(evt);
            }
        });
        jPanel1.add(jlogin2);
        jlogin2.setBounds(530, 650, 396, 52);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorycashierinsystem/img/page.png"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, -20, 1110, 850);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1107, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasswordActionPerformed

    private void jlogin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlogin1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlogin1MouseClicked

    private void jlogin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlogin2MouseClicked
        // TODO add your handling code here:
// this is for the sign in; 
        String firstname = jfirstname.getText();
        String lastname = jlastname.getText();
        String email    = jemail.getText();
        String password = String.valueOf(jpassword.getPassword());
        String role = jrole.getSelectedItem().toString();
        String status   = "InActive";

               

                try{
                   String Sign_inQuery = "INSERT INTO `users`(`FirstName`, `LastName`, `Email`, `Password`, `Role`, `Status`) VALUES (?,?,?,?,?,?)";
                    pst.setString(1, firstname);
                    pst.setString(2, lastname);
                    pst.setString(3, email);
                    pst.setString(4, password);
                    pst.setString(5, role);
                    pst.setString(6, status);

                    if(pst.executeUpdate() !=0){
                        JOptionPane.showMessageDialog(null, "You acount is added to the system ");
                        JOptionPane.showMessageDialog(null, "Just wait for Approval by your Admin");
                        new LogIn_Page().setVisible(true);
                        setVisible(false);
 
                            }else{
                                JOptionPane.showMessageDialog(null, "ERROR");
                            }

                }catch(SQLException ex){
                 JOptionPane.showMessageDialog(null, "ERRO");
                }

    }//GEN-LAST:event_jlogin2MouseClicked

    private void jlogin3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlogin3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlogin3MouseClicked

    private void jlogin4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlogin4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlogin4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        new LogIn_Page().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jemail;
    private javax.swing.JTextField jfirstname;
    private javax.swing.JTextField jlastname;
    private javax.swing.JLabel jlogin1;
    private javax.swing.JLabel jlogin2;
    private javax.swing.JLabel jlogin3;
    private javax.swing.JLabel jlogin4;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JComboBox<String> jrole;
    // End of variables declaration//GEN-END:variables
}
